// Copyright 2026 Element Creations Ltd.
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
// Please see LICENSE files in the repository root for full details.

//! Build script for `mas-build-info`.
//!
//! This generates path constants based on build-time environment variables:
//!
//! - `MAS_SHARE_DIR`: Base directory for all resources (packaged mode)
//! - Individual overrides: `MAS_TEMPLATES_PATH`, `MAS_ASSETS_PATH`, etc.
//!
//! When `MAS_SHARE_DIR` is not set, dev mode defaults are used (source tree
//! paths).

use std::{env, fs, path::PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Get the share directory if set (packaged mode)
    let share_dir = env::var("MAS_SHARE_DIR").ok();

    // Determine each path, with individual overrides taking precedence
    let templates_path = env::var("MAS_TEMPLATES_PATH").ok().unwrap_or_else(|| {
        share_dir
            .as_ref()
            .map(|s| format!("{s}/templates/"))
            .unwrap_or_else(|| "./templates/".to_owned())
    });

    let assets_path = env::var("MAS_ASSETS_PATH").ok().unwrap_or_else(|| {
        share_dir
            .as_ref()
            .map(|s| format!("{s}/assets/"))
            .unwrap_or_else(|| "./frontend/dist/".to_owned())
    });

    let assets_manifest_path =
        env::var("MAS_ASSETS_MANIFEST_PATH").ok().unwrap_or_else(|| {
            share_dir
                .as_ref()
                .map(|s| format!("{s}/manifest.json"))
                .unwrap_or_else(|| "./frontend/dist/manifest.json".to_owned())
        });

    let translations_path = env::var("MAS_TRANSLATIONS_PATH").ok().unwrap_or_else(|| {
        share_dir
            .as_ref()
            .map(|s| format!("{s}/translations/"))
            .unwrap_or_else(|| "./translations/".to_owned())
    });

    let policy_path = env::var("MAS_POLICY_PATH").ok().unwrap_or_else(|| {
        share_dir
            .as_ref()
            .map(|s| format!("{s}/policy.wasm"))
            .unwrap_or_else(|| "./policies/policy.wasm".to_owned())
    });

    // Generate the Rust code
    let code = format!(
        r#"// Generated by build.rs - do not edit manually

/// Default path to the templates directory.
pub const DEFAULT_TEMPLATES_PATH: &str = {templates_path:?};

/// Default path to the assets directory.
pub const DEFAULT_ASSETS_PATH: &str = {assets_path:?};

/// Default path to the assets manifest file.
pub const DEFAULT_ASSETS_MANIFEST_PATH: &str = {assets_manifest_path:?};

/// Default path to the translations directory.
pub const DEFAULT_TRANSLATIONS_PATH: &str = {translations_path:?};

/// Default path to the policy WASM module.
pub const DEFAULT_POLICY_PATH: &str = {policy_path:?};
"#
    );

    fs::write(out_dir.join("paths.rs"), code).expect("Failed to write generated paths.rs");

    // Re-run if any of these env vars change
    println!("cargo::rerun-if-env-changed=MAS_SHARE_DIR");
    println!("cargo::rerun-if-env-changed=MAS_TEMPLATES_PATH");
    println!("cargo::rerun-if-env-changed=MAS_ASSETS_PATH");
    println!("cargo::rerun-if-env-changed=MAS_ASSETS_MANIFEST_PATH");
    println!("cargo::rerun-if-env-changed=MAS_TRANSLATIONS_PATH");
    println!("cargo::rerun-if-env-changed=MAS_POLICY_PATH");
}
