{
 "title": "matrix-authentication-service",
 "description": "A dashboard for monitoring matrix-authentication-service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "label_values(target_info, job)" },
   {
    "name": "instance",
    "query": "label_values(target_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service_version) (target_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{service_version}}"
    }
   ]
  },
  {
   "title": "Tokio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(tokio_runtime_workers{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Tick Time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "sum by (le) (irate(tokio_runtime_worker_poll_time_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Tick Time Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (irate(tokio_runtime_worker_poll_time_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (irate(tokio_runtime_worker_poll_time_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (irate(tokio_runtime_worker_poll_time_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (irate(tokio_runtime_worker_poll_time_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Poll Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(tokio_runtime_worker_polls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Polls"
      }
     ]
    },
    {
     "title": "Active Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "tasks" } },
     "targets": [
      {
       "expr": "sum(tokio_runtime_alive_tasks{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Active Tasks"
      }
     ]
    },
    {
     "title": "Busy Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(tokio_runtime_worker_busy_duration_milliseconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Worker busy Time"
      }
     ]
    }
   ]
  },
  { "title": "HTTP server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route, http_response_status_code )\n(irate(http_server_duration_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{http_request_method}} {{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route, http_response_status_code)\n(irate(http_server_duration_count{job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]))\n",
     "legendFormat": "{{http_request_method}} {{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Request latency (excluding introspection)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route!=\"/oauth2/introspect\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Request latency percentiles (excluding introspection)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route!=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route!=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route!=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route!=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Request latency (introspection only)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route=\"/oauth2/introspect\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Request latency percentiles (introspection only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  irate(http_server_duration_bucket{job=~\"$job\", instance=~\"$instance\", http_route=\"/oauth2/introspect\"}[$__rate_interval])\n))\n",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Database connection acquisition latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 301 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(db_client_connections_create_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Database connection acquisition latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  irate(db_client_connections_create_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  irate(db_client_connections_create_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n  irate(db_client_connections_create_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  irate(db_client_connections_create_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Database connection pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 301 },
   "targets": [
    {
     "expr": "sum by (state) (db_connections_usage{job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "Connection {{state}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "Job run duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 401 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(job_process_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Job run P95 per type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job_queue_name) (\n  irate(job_process_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "{{job_queue_name}}"
    }
   ]
  },
  {
   "title": "Job runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(job_queue_name, job_result)\n(irate(job_process_duration_milliseconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job_queue_name}} {{job_result}}"
    }
   ]
  },
  {
   "title": "Worker tick duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 409 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(job_worker_tick_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Worker tick duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 409 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  irate(job_worker_tick_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  irate(job_worker_tick_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n  irate(job_worker_tick_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  irate(job_worker_tick_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Activity tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Record rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(session_kind)\n(irate(mas_activity_tracker_messages_total{job=~\"$job\", instance=~\"$instance\", type=\"record\"}[$__rate_interval]))\n",
     "legendFormat": "{{session_kind}}"
    }
   ]
  },
  {
   "title": "Flush time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 501 },
   "targets": [
    {
     "expr": "sum by (le) (\n  irate(mas_activity_tracker_flush_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Flush time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  irate(mas_activity_tracker_flush_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  irate(mas_activity_tracker_flush_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n  irate(mas_activity_tracker_flush_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  irate(mas_activity_tracker_flush_time_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n))\n",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}