# Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.

rules:
  imports:
    unresolved-reference:
      level: ignore
  style:
    external-reference:
      level: ignore
    line-length:
      level: ignore
