# Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.

name: Build the frontend assets
description: Installs Node.js and builds the frontend assets from the frontend directory

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v4.2.0
      with:
        node-version: "22"

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
      shell: sh

    - name: Build the frontend assets
      run: npm run build
      working-directory: ./frontend
      shell: sh
