# Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.

name: Build the frontend assets
description: Installs Node.js and builds the frontend assets from the frontend directory

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6.0.5

    - name: Install Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: .node-version
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: sh

    - name: Build the frontend assets
      run: pnpm --filter mas-frontend run build
      shell: sh
