# Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.

name: Download translation files from Localazy
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Fail the workflow if not on the main branch or a release branch
        if: ${{ !(startsWith(github.ref_name, 'release/v') || github.ref_name == 'main') }}
        run: exit 1

      - name: Checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Install Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compute the Localazy branch name
        id: branch
        # This will strip the "release/" prefix if present, keeping 'main' as-is
        run: echo "name=${GITHUB_REF_NAME#release/}" >> "$GITHUB_OUTPUT"

      - name: Download translations from Localazy
        run: pnpm exec localazy download -w "$LOCALAZY_WRITE_KEY" -b "$BRANCH"
        env:
          LOCALAZY_WRITE_KEY: ${{ secrets.LOCALAZY_WRITE_KEY }}
          BRANCH: ${{ steps.branch.outputs.name }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          sign-commits: true
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          branch: actions/localazy-download/${{ steps.branch.outputs.name }}
          delete-branch: true
          title: Translations updates for ${{ steps.branch.outputs.name }}
          labels: |
            T-Task
            A-I18n
          commit-message: Translations updates

      - name: Enable automerge
        run: gh pr merge --merge --auto "$PR_NUMBER"
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
